spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d93aa51830029f34b63f
            clientSecret: dc270387970fc32dc5f326bced0a302ca435926b
          google:
            client-id: 166729237672-sk6a0k0cjvji35ovpi9db12d22jlnp49.apps.googleusercontent.com
            client-secret: sji7IQl_E8ctaWUpZ64OVwDD
          kakao:
            client-id: 6f1efef68f605ec7ed94f033ab1ad172
            client-secret: seeSIUrIyvjaHRHQmaBJIUZh6PZOmdge
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id